name: LLM
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py312h06a4308_0
  - numpy-base=2.1.3=py312h0da6c21_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.16=h5eee18b_0
  - pillow=11.1.0=py312hcea889d_0
  - pip=24.0=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.3=h996f2a0_1
  - pytorch=2.5.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py312h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - setuptools=69.5.1=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.5.1=py312_cu124
  - torchtriton=3.1.0=py312
  - torchvision=0.20.1=py312_cu124
  - typing_extensions=4.11.0=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - absl-py==2.1.0
    - accelerate==1.2.1
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - attrs==23.2.0
    - audioread==3.0.1
    - backoff==2.2.1
    - biopython==1.85
    - bitsandbytes==0.45.0
    - blis==1.2.0
    - catalogue==2.0.10
    - certifi==2024.6.2
    - cffi==1.16.0
    - click==8.1.8
    - cloudpathlib==0.21.0
    - coloredlogs==15.0.1
    - confection==0.1.5
    - contourpy==1.3.1
    - cycler==0.12.1
    - cymem==2.0.11
    - dataclassy==1.0.1
    - datasets==2.20.0
    - decorator==5.1.1
    - dill==0.3.8
    - distance==0.1.3
    - editdistance==0.8.1
    - einops==0.8.0
    - filelock==3.15.1
    - fire==0.7.0
    - flash-attn==2.7.3
    - flatbuffers==25.2.10
    - fonttools==4.55.8
    - frozenlist==1.4.1
    - fsspec==2024.5.0
    - g2p-en==2.1.0
    - greenlet==3.2.2
    - grpcio==1.68.1
    - h5py==3.13.0
    - huggingface-hub==0.27.0
    - humanfriendly==10.0
    - indic-numtowords==1.0.2
    - inflect==7.5.0
    - jiwer==3.0.5
    - joblib==1.4.2
    - kaldiio==2.18.0
    - kiwisolver==1.4.8
    - kneed==0.8.5
    - langcodes==3.5.0
    - language-data==1.3.0
    - lazy-loader==0.4
    - levenshtein==0.26.1
    - librosa==0.11.0
    - llvmlite==0.43.0
    - marisa-trie==1.2.1
    - markdown==3.7
    - markdown-it-py==3.0.0
    - matplotlib==3.10.0
    - mdurl==0.1.2
    - more-itertools==10.7.0
    - msgpack==1.0.8
    - multidict==6.0.5
    - multiprocess==0.70.16
    - munkres==1.1.4
    - murmurhash==1.0.12
    - nl-core-news-sm==3.8.0
    - nltk==3.9.1
    - numba==0.60.0
    - numpy==2.0.0
    - onnxruntime==1.22.0
    - packaging==24.1
    - pandas==2.2.2
    - panphon==0.21.2
    - peft==0.14.0
    - platformdirs==4.2.2
    - pooch==1.8.2
    - praatio==6.2.0
    - preshed==3.0.9
    - protobuf==5.29.2
    - psutil==5.9.8
    - pyarrow==16.1.0
    - pyarrow-hotfix==0.6
    - pycparser==2.22
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pygments==2.19.1
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - python-levenshtein==0.26.1
    - pytz==2024.1
    - rapidfuzz==3.11.0
    - regex==2024.5.15
    - rich==13.9.4
    - rich-click==1.8.9
    - safetensors==0.4.3
    - scikit-learn==1.5.0
    - scipy==1.14.0
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - shellingham==1.5.4
    - six==1.16.0
    - smart-open==7.1.0
    - soundfile==0.12.1
    - soxr==0.5.0.post1
    - spacy==3.8.4
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - sqlalchemy==2.0.41
    - srsly==2.5.1
    - sympy==1.13.1
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - termcolor==2.5.0
    - thinc==8.3.4
    - threadpoolctl==3.5.0
    - tokenizers==0.20.3
    - torch-complex==0.4.4
    - tqdm==4.66.4
    - transformers==4.46.3
    - typeguard==4.4.2
    - typer==0.15.2
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - unicodecsv==0.14.1
    - urllib3==2.2.1
    - vptree==1.3
    - wasabi==1.1.3
    - weasel==0.4.1
    - werkzeug==3.1.3
    - whisper-normalizer==0.1.11
    - wrapt==1.17.2
    - xxhash==3.4.1
    - yarl==1.9.4
prefix: /esat/spchtemp/scratch/jponcele/anaconda3/envs/LLM
